# Generated by Django 5.2 on 2025-04-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_answer_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
